# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

[[main]]
  name = "News"
  url = "#posts"
  weight = 20

[[main]]
  name = "Research"
  identifier = "Project"
  url = "#projects"
  weight = 25

  [[main]]
    name = "Overview"
    parent = "Project"
    url = "#projects"
    weight = 25

  [[main]]
    name = "Crop Epigenetics"
    parent = "Project"
    url = "project/crop_epigenetics"
    weight = 31

  [[main]]
    name = "Epigenomic Signatures"
    parent = "Project"
    url = "project/umr-distilling-functional-elements"
    weight = 32

  [[main]]
    name = "Stress Resilience"
    parent = "Project"
    url = "project/stress"
    weight = 33

[[main]]
  name = "People"
  url = "#people"
  weight = 40

[[main]]
  name = "Publications"
  url = "#featured"
  weight = 50

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
